# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('testimonials', 'Tesimonials'), ('gallery', 'Gallery'), ('contact', 'Contact')], default=None, max_length=255)),
                ('upload', models.ImageField(upload_to='<django.db.models.fields.CharField>/uploads')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=254)),
                ('email_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Carpentry', 'Carpentry'), ('Landscaping', 'Landscaping'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default=None, max_length=15)),
                ('description', models.TextField()),
            ],
        ),
    ]
