# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('upload', models.ImageField(upload_to='<django.db.models.fields.CharField>/uploads')),
                ('picture_position', models.CharField(choices=[('Top', 'Top'), ('Left', 'Left'), ('Right', 'Right'), ('Bottom', 'Bottom')], default=None, max_length=5)),
                ('article_content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RenameField(
            model_name='page',
            old_name='paragraph',
            new_name='main_content',
        ),
        migrations.AddField(
            model_name='page',
            name='picture_position',
            field=models.CharField(choices=[('Top', 'Top'), ('Left', 'Left'), ('Right', 'Right'), ('Bottom', 'Bottom')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Page'),
        ),
    ]
